[package]
authors = ["Tim_Paik <timpaikc@outlook.com>"]
description = "simple http server written in rust"
edition = "2018"
name = "web"
version = "0.1.7-beta"

[dependencies]
chrono = "0.4"
clap = {version = "3.0.0-beta.2", features = ["wrap_help", "color"]}
colored = "2"
lazy_static = "1.4.0"
rocket = {version = "0.5.0-rc.1", features = ["tls"]}
rocket_dyn_templates = {version = "0.1.0-rc.1", features = ["tera"]}
